version: '3.4'

services:
  php:
    build:
      context: ./api
      target: api_php
    image: php:8.0-fpm-alpine
    volumes:
      - ./api:/srv/api_rw,cached
      - ./api/var:/srv/var:rw

  api:
    build:
      context: ./api
      target: api_nginx
    image: nginx:stable-alpine
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    ports:
      - "8088:80"


  vue-ui:
    build:
      context: ./front
    ports:
      - "5000:8080"
    volumes:
      - ./front:/usr/src/app/front
      - /usr/src/app/front/node_modules
