name: CI

on:
  - pull_request

jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHP syntax checker 7.3
        uses: overtrue/phplint@master
        with:
           path: ./api/
           options: --exclude=*.log
           warning: true
      - name: Pull images
        run: docker-compose pull
      - name: Start services
        run: make build
      - name: Wait for services
        run: |
              while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose ps -q php)")"; do
                case $status in
                  starting) sleep 1;;
                  healthy) exit 0;;
                  unhealthy) exit 1;;
                esac
              done
              exit 1
#       - name: Setup Rabbit
#         run: docker-compose exec -T php bin/console rabbitmq:setup-fabric
      - name: JWT pems
        run: docker-compose exec -T php sh -c ' set -e; apk add openssl; mkdir -p config/jwt; jwt_passphrase=${JWT_PASSPHRASE:-$(grep ''^JWT_PASSPHRASE='' .env.dist | cut -f 2 -d ''='')} ;echo "$jwt_passphrase" | openssl genpkey -out config/jwt/private.pem -pass stdin -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 ; echo "$jwt_passphrase" | openssl pkey -in config/jwt/private.pem -passin stdin -out config/jwt/public.pem -pubout ; setfacl -R -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt ; setfacl -dR -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt'
      - name: Test
        run:  make tests


