name: Code Style

on: [push]

jobs:
  php_cs_fixer:
    name: Improve style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHP CS Fixer
        uses: ./.github/actions/clean_code
      - name: Commit CS Fixer changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
